<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <IncludeBuildOutput>False</IncludeBuildOutput>
    <GenerateAssemblyInfo>False</GenerateAssemblyInfo>
    <GenerateDocumentationFile>False</GenerateDocumentationFile>
    <CopyBuildOutputToOutputDirectory>False</CopyBuildOutputToOutputDirectory>
    <CopyOutputSymbolsToOutputDirectory>False</CopyOutputSymbolsToOutputDirectory>
    <Description>SD.Framework PCL运行时-Linux-x64</Description>
  </PropertyGroup>

  <ItemGroup>
    <None Include="Package.props">
      <Pack>True</Pack>
      <PackagePath>build\netstandard2.0\$(PackageId).props</PackagePath>
    </None>
    <None Include="$(SolutionDir)\runtimes\linux-x64\lib\*.so">
      <Visible>False</Visible>
      <Pack>True</Pack>
      <PackagePath>runtimes\linux-x64\</PackagePath>
    </None>
  </ItemGroup>
</Project>
