<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <OutputType>WinExe</OutputType>
    <IsPackable>False</IsPackable>
    <UseWPF>True</UseWPF>
    <ApplicationIcon>favicon.ico</ApplicationIcon>
    <Description>SD.Framework PCL客户端</Description>
  </PropertyGroup>

  <PropertyGroup>
    <PlatformTarget>AnyCPU</PlatformTarget>
    <DebugType>Full</DebugType>
    <DebugSymbols>True</DebugSymbols>
  </PropertyGroup>

  <ItemGroup>
    <Resource Include="favicon.ico" />
    <Resource Include="Content\Images\PCL.png" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MahApps.Metro" Version="2.4.11" />
    <PackageReference Include="MahApps.Metro.IconPacks.MaterialDesign" Version="6.2.1" />
    <PackageReference Include="FluentWPF" Version="0.10.2" />
    <PackageReference Include="BusyIndicator" Version="1.9.0">
      <ExcludeAssets>contentFiles</ExcludeAssets>
    </PackageReference>
    <PackageReference Include="HelixToolkit.Wpf.SharpDX" Version="3.1.2" />
    <PackageReference Include="SkiaSharp" Version="3.119.1" />
    <PackageReference Include="SkiaSharp.Views.WPF" Version="3.119.1" />
    <PackageReference Include="MrAdvice" Version="2.19.1" />
    <PackageReference Include="SD.Common" Version="3.4.1" />
    <PackageReference Include="SD.Toolkits.Mathematics" Version="1.0.0" />
    <PackageReference Include="SD.IOC.Core" Version="1.3.3" />
    <PackageReference Include="SD.Infrastructure" Version="3.8.3" />
    <PackageReference Include="SD.Infrastructure.WPF" Version="1.8.0" />
    <PackageReference Include="SD.Infrastructure.WPF.3D" Version="1.1.1" />
    <PackageReference Include="SD.Infrastructure.WPF.Caliburn" Version="1.4.0" />
  </ItemGroup>

  <!--NuGet引用SDK-->

  <!--项目引用SDK-->
  <ItemGroup>
    <ProjectReference Include="..\PCLSharp.Primitives\PCLSharp.Primitives.csproj" />
    <ProjectReference Include="..\PCLSharp.Modules\PCLSharp.Modules.csproj" />
    <ProjectReference Include="..\PCLSharp.Extensions.Helix\PCLSharp.Extensions.Helix.csproj" />
    <ProjectReference Include="..\PCLSharp.Extensions.Plotter\PCLSharp.Extensions.Plotter.csproj" />
  </ItemGroup>
</Project>
