<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net462;netstandard2.0</TargetFrameworks>
    <LangVersion>8.0</LangVersion>
    <Description>SD.Framework PCL绘图扩展</Description>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="SkiaSharp" Version="3.119.1" />
    <PackageReference Include="ScottPlot" Version="5.1.57" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\PCLSharp.Primitives\PCLSharp.Primitives.csproj" />
  </ItemGroup>
</Project>
